#pragma once
// Auto-generated by train_and_export.py. Do not edit manually.
const int NUM_CLASSES = 5;
const char* const CLASS_NAMES[NUM_CLASSES] = {
  "cube_soft",
  "cube_stiff",
  "cylinder_soft",
  "cylinder_stiff",
  "no_object",
};
